# Use the official Jaeger all-in-one image as the base
FROM jaegertracing/all-in-one:latest

#ENV COLLECTOR_OTLP_GRPC_HOST_PORT=0.0.0.0:4317

# Expose ports for the Jaeger services
EXPOSE 4317
EXPOSE 16686