services:
  prom.sample.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "7000:8080"
      - "7060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  prom.sample.monitor:
    ports:
    - "9090:9090"
  prom.sample.visualizer:
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana  # Optional: Persist data