services:
  observability.web:
    image: ${DOCKER_REGISTRY-}promsampleweb
    build:
      context: ./observability.web
      dockerfile: Dockerfile
    networks:
      - monitoring
  observability.prometheus:
    build:
      context: ./observability.prometheus
      dockerfile: Dockerfile
    networks:
      - monitoring
  observability.grafana:
    build:
      context: ./observability.grafana
      dockerfile: Dockerfile
    depends_on:
      - observability.prometheus
    networks:
      - monitoring
  observability.jaeger:
    build:
        context: ./observability.jaeger
        dockerfile: Dockerfile
    depends_on:
        - observability.prometheus
    networks:
        - monitoring
networks:
  monitoring:
    driver: bridge