services:
  prom.sample.web:
    image: ${DOCKER_REGISTRY-}promsampleweb
    build:
      context: ./prom.sample.web
      dockerfile: Dockerfile
    networks:
      - monitoring
  prom.sample.monitor:
    build:
      context: ./prom.sample.monitor
      dockerfile: Dockerfile
    networks:
      - monitoring
  prom.sample.visualizer:
    build:
      context: ./prom.sample.visualizer
      dockerfile: Dockerfile
    depends_on:
      - prom.sample.monitor
    networks:
      - monitoring
  observability.sample.traces:
    build:
        context: ./observability.sample.traces
        dockerfile: Dockerfile
    depends_on:
        - prom.sample.monitor
    networks:
        - monitoring
networks:
  monitoring:
    driver: bridge