services:
  prom.sample.web:
    image: ${DOCKER_REGISTRY-}promsampleweb
    build:
      context: ./prom.sample.web
      dockerfile: Dockerfile
    networks:
      - monitoring
  prometheus:
    build:
      context: ./prom.sample.monitor
      dockerfile: Dockerfile
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge