FROM grafana/grafana:latest

# Add custom plugins or configuration (if needed)
# Example: COPY custom.ini /etc/grafana/custom.ini

EXPOSE 3000

CMD ["grafana-server", "--homepath=/usr/share/grafana", "--config=/etc/grafana/grafana.ini"]
